### ISSUE TITLE
No way to catch :server or ENV['domain']

### ISSUE THREAD

**Issue by alvesoaj** [Juanmcuello/mina-multi_server#1]
How to get server info, instead of servers array? Like select task?

**Comment by Juanmcuello** [comment]
The thing is that setting `ENV['domain']` is delayed until the last moment, when the commands are sent to the server. This makes not possible to get the domain in a previous moment. 

I' ll try to figure out a way to keep the current behavior and still be able to access the domain inside other tasks .

**Comment by Juanmcuello** [comment]
Due to how Mina works, there is no an easy way to get what you need. Just to know, why do you need to get the `server` setting?

**Comment by alvesoaj** [comment]
Ok, I need to know the server to run a especific task just to one server. Now, first I run:

`mina production deploy`

and after:

`mina production select delayed_job:restart`

It works, but I wish to run in one shot.
No problem, I will figure out how to do It in a other way.

Really thank you for you attention!!!

**Comment by Juanmcuello** [comment]
I think you can at least avoid having to select the server interactively, creating a new task in your deploy.rb:
```ruby
task :restart_delayed_job do
  # Let's say the last server in your servers array is the one that runs delayed_job
  set :servers, [fetch(:servers).last]
  invoke :'delayed_job:restart'
end
```
```console
$ mina production deploy
$ mina production restart_delayed_job
```
You can go a little further and create a bash script `deploy.sh` in order to automate the two tasks above:

```bash
#!/bin/bash

if [ -z ${1+x} ]
then
  echo No stage was specified
else
  mina $1 deploy;
  mina $1 restart_delayed_job;
fi
```
```console
$ chmod +x deploy.sh
```

Then, anytime you want to deploy, you can do:
```
$ ./deploy.sh production
```

**Comment by alvesoaj** [comment]
Thank you one more time!
