### ISSUE TITLE
How to deploy and manage web processes (puma, nginx) on one set of servers, and worker processes(resque / sidekiq) on other set of servers?

### ISSUE THREAD

**Issue by 8parth** [Juanmcuello/mina-multi_server#2]
We are using mina for production. I want to deploy and manage nginx and puma on one set of servers, and sidekiq on other set of servers. How can I achieve this with mina-multi_server? Is there anything similar to roles?

**Comment by Juanmcuello** [comment]
There is no such a thing as roles, but maybe having different tasks could solve what you need. 
Something like this:

```ruby
task :web do
  set :servers, ['www1.example.com', 'www2.example.com']
end

task :workers do
  set :servers, ['worker1.example.com', 'worker2.example.com']
end
```

Then you can call the two tasks (assuming there are tasks named `deploy`):

```console
$ mina web deploy
$ mina workers deploy
```

If you want, you can create a bash script in order to run just one command. See  #1 to see how.
